### ISSUE TITLE
incorrect constant naming

### ISSUE THREAD

**Issue by danmarsden** [k-rokicki/moodle-assignfeedback_grades_chart#1]
https://github.com/k-rokicki/moodle-assignfeedback_grades_chart/blob/master/locallib.php#L33-L38

These could conflict with core constants  - please see our naming conventions here:
https://docs.moodle.org/dev/Frankenstyle#Constants

**Comment by k-rokicki** [comment]
Fixed in da9d47a7a22147bcce5a13c30a20135695f3a01f- thanks!

**Comment by danmarsden** [comment]
cool - much nicer sitting inside the class... FYI - if it's in the class you don't actually have to use the frankenstyle prefix as the constants are part of the class rather in the global scope. :-)

**Comment by k-rokicki** [comment]
oh, I thought so, but I wasn't sure if there is a naming convention for class constants - I'll probably change that when testing with Moodle 4 :)
