### ISSUE TITLE
plugin name length may prevent using tables within the plugin in future.

### ISSUE THREAD

**Issue by danmarsden** [k-rokicki/moodle-assignfeedback_grades_chart#2]
This is really an informational issue - so feel free to close, but it's probably important to know for any other future plugins you might create.

Your frankenstyle plugin name is very long (assignfeedback_grades_chart) - Moodle database tables have a limit of 28 characters and any tables you implement inside your plugin must be prefixed with the frankenstyle name - your name is 27 characters which means that you would find it difficult to implement many tables within this plugin in future.

Also keep in mind there is no easy way to "rename" a plugin once it's installed on a site and you can't rename plugins in the plugins db either so it's important to try and use shorter names where possible :-)

thanks!

**Comment by k-rokicki** [comment]
Thank you for the reminder! I don't plan on adding tables with this plugin, but I'll try to keep my upcoming plugin names short :)
