### ISSUE TITLE
privacy provider class looks incorrect

### ISSUE THREAD

**Issue by danmarsden** [k-rokicki/moodle-assignfeedback_grades_chart#4]
I think you really just need a null provider in there - like the offline feedback plugin;
https://github.com/moodle/moodle/blob/master/mod/assign/feedback/offline/classes/privacy/provider.php

more info on privacy providers is here:
https://docs.moodle.org/dev/Privacy_API

**Comment by k-rokicki** [comment]
Yes, my mistake - thanks! Fixed in 722ec72bb475adbf1a9e43844b154c9d60c64944
